// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKogrOtRbbMmoIZYKiV_ICVHBPlN4wJdE',
    appId: '1:38103098921:web:2466b971c3d4dbef8d1e38',
    messagingSenderId: '38103098921',
    projectId: 'smart-pantry-8562c',
    authDomain: 'smart-pantry-8562c.firebaseapp.com',
    storageBucket: 'smart-pantry-8562c.firebasestorage.app',
    measurementId: 'G-7ZTPRL00K2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnfHItHNv3TQ_YXA_dd4VSk3pOMWzOkLQ',
    appId: '1:38103098921:android:1b3f821ea9c4d09f8d1e38',
    messagingSenderId: '38103098921',
    projectId: 'smart-pantry-8562c',
    storageBucket: 'smart-pantry-8562c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnawFKmIyHnD9O8bPd5C1P1xSbjrFj2Go',
    appId: '1:38103098921:ios:2cc973b5961fba0c8d1e38',
    messagingSenderId: '38103098921',
    projectId: 'smart-pantry-8562c',
    storageBucket: 'smart-pantry-8562c.firebasestorage.app',
    iosBundleId: 'com.example.recipeAppFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnawFKmIyHnD9O8bPd5C1P1xSbjrFj2Go',
    appId: '1:38103098921:ios:2cc973b5961fba0c8d1e38',
    messagingSenderId: '38103098921',
    projectId: 'smart-pantry-8562c',
    storageBucket: 'smart-pantry-8562c.firebasestorage.app',
    iosBundleId: 'com.example.recipeAppFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKogrOtRbbMmoIZYKiV_ICVHBPlN4wJdE',
    appId: '1:38103098921:web:b5650fd8865e86178d1e38',
    messagingSenderId: '38103098921',
    projectId: 'smart-pantry-8562c',
    authDomain: 'smart-pantry-8562c.firebaseapp.com',
    storageBucket: 'smart-pantry-8562c.firebasestorage.app',
    measurementId: 'G-XKP250QJVB',
  );
}
